const randomId = Math.random() * 10000

export const products = [
	{
		name: "Berg Favorit 330cm",
		price: 4999,
		picture: "https://scale.coolshop-cdn.com/product-media.coolshop-cdn.com/AG4M9N/9c6e6d22e5bc45e2860cab8770776fac.jpeg/f/berg-favorit-330cm-studsmatta-saekerhetsnaet-deluxe.jpeg",
		description: "En högkvalitativ studsmatta för hela familjen. Tillverkad med UV-resistent och vattenavvisande material för extra hållbarhet. Inkluderar en robust skyddsnät.",
		id: randomId,
	},
	{
		name: "JumpPower Deluxe 305cm",
		price: 3499,
		picture: "https://giocofuori.it/wp-content/uploads/2021/12/page-original-JP10-2.jpg",
		description: "En stabil studsmatta med en viktgräns på 150 kg. Inkluderar en säkerhetsnät, stege och regnskydd. Den robusta ramen gör den lämplig för intensivt hoppande.",
		id: randomId,
	},
	{
		name: "Springfree Trampoline 10ft",
		price: 14999,
		picture: "https://www.creativeplaythings.com/media/catalog/product/cache/a1f3f640150dcb6df0803e8f61717e2c/r/7/r79_KrMMyPXGjAxu7FmI.jpg",
		description: "En studsmatta med en unik ramdesign som eliminerar stålfjädrarna för att minska skaderisken. Inkluderar en flexibel skyddsnät och mjuk kant runt studsmattan.",
		id: randomId,
	},
	{
		name: "Berg Champion 430cm",
		price: 8299,
		picture: "https://www.bäst-i-test.se/assets/product-images/new-product-page-8/Berg-Champion-430-cm.jpg",
		description: "En högkvalitativ studsmatta med en extra bred kant för extra stabilitet och säkerhet. Inkluderar en robust skyddsnät och en bekväm stege för enkel åtkomst.",
		id: randomId,
	},
	{
		name: "JumpSport Elite 14ft",
		price: 11999,
		picture: "https://leisureinstalls.com/wp-content/uploads/2020/03/JumpSport-ELITE-Trampoline-12ft_01__34228.1495056913.jpg",
		description: "En studsmatta med en innovativ hoppyta som minskar trycket på kroppen för att minska risken för skador. Inkluderar en högkvalitativ ram och enkel montering.",
		id: randomId,
	},
	{
		name: "Exit JumpArena 305cm",
		price: 3299,
		picture: "https://www.exittoys.se/604/0/0/1/ffffff00/ee3a4d1f/ff48c3713cf1956b048c04fe538a122a482a8d26f367d6a0ea24d1223aa6d436/10-95-14-02-exit-jumparena-trampoline-oval-305x427cm-with-ladder-and-shoe-bag-green.jpg",
		description: "En studsmatta med en stark ram och en bekväm stege för enkel åtkomst. Inkluderar en högkvalitativ säkerhetsnät och en mjuk kant för extra säkerhet.",
		id: randomId,
	},
	{
		name: "Springfree Trampoline 13ft",
		price: 19999,
		picture: "https://media-www.canadiantire.ca/product/seasonal-gardening/backyard-fun/backyard-amusement/0846845/springfree-jumbo-trampoline-13--aebdcacc-a072-47a8-9182-41701f606f26.png",
		description: "En studsmatta med en unik design utan farliga fjädrar som kan skada användaren. Istället för fjädrar använder denna trampolin FlexiNet och FlexiEdge-teknik som ger en mjukare landning och maximal säkerhet",
		id: randomId,
	},
	{
		name: "Berg Elite+ 430cm",
		price: 11999,
		picture: "https://cdn.abicart.com/shop/25154/art54/h9540/26179540-origpic-406ada.jpg",
		description: "En studsmatta i premiumklassen med en extra tjock kant och en unik ramkonstruktion för extra stabilitet. Inkluderar en robust skyddsnät och en bekväm stege.",
		id: randomId,
	},
	{
		name: "JumpSport 12ft StagedBounce",
		price: 8999,
		picture: "https://m.media-amazon.com/images/I/A1vaKEBLKnL._AC_UF1000,1000_QL80_.jpg",
		description: "En studsmatta med en innovativ fjädringsteknik som ger en jämnare studs och minskar risken för skador. Inkluderar en högkvalitativ ram och enkel montering.",
		id: randomId,
	},
	{
		name: "Exit Supreme 244cm",
		price: 2199,
		picture: "https://img.babymarkt.com/isa/163853/c3/detailpage_desktop_600/-/bf5b48fc9f3645e28ecd71e182b315a0/exit-trampolin-siluett-o-244cm-groen-a251724",
		description: "En kompakt studsmatta som passar perfekt för mindre trädgårdar eller ytor. Inkluderar en högkvalitativ säkerhetsnät och en mjuk kant för extra säkerhet.",
		id: randomId,
	},
	{
		name: "Berg Ultim Champion 330cm",
		price: 6499,
		picture: "https://resources.sport-tiedje.com/bilder/bergtoys/trampoline/ultim-champion/berg-ultim-champion-regular-deluxe-grau_600.jpg",
		description: "En studsmatta med en extra kraftig ram och en bred kant för extra stabilitet och säkerhet. Inkluderar en robust skyddsnät och en bekväm stege.",
		id: randomId,
	},
	{
		name: "JumpKing 14ft",
		price: 8499,
		picture: "https://i5.walmartimages.com/asr/e230838b-1a36-46bc-8a41-7c0007e8aa64.ddbd614ff42096aeca5ac2433b8fa738.jpeg",
		description: "En studsmatta med en kraftig och rostfri ram som tål tufft användande. Inkluderar en högkvalitativ säkerhetsnät och en mjuk kant för extra säkerhet.",
		id: randomId,
	},
	{
		name: "Berg Favorit InGround 330cm",
		price: 5699,
		picture: "https://www.bäst-i-test.se/assets/product-images/test-berg-favorit-inground-comfort-330-cm/Berg-Favorit-InGround-Comfort-330-cm2.jpg",
		description: "En studsmatta som kan grävas ner i marken för en mer diskret placering. Inkluderar en stark ram och en robust skyddsnät för extra säkerhet.",
		id: randomId,
	},
	{
		name: "Skyhigh Deluxe 305cm",
		price: 2999,
		picture: "https://www.exittoys.se/604/0/0/1/ffffff00/ee3a4d1f/00439b6716d877ac8f2c5d3d3caa1176473de0685376d0666e61d5b24a3086d6/exit-lotus-classic-studsmatta-o305cm-gron.jpg",
		description: "En stabil studsmatta med en kraftig ram och en mjuk kant för extra säkerhet. Inkluderar en högkvalitativ säkerhetsnät och en bekväm stege.",
		id: randomId,
	},
	{
		name: "JumpKing Air 15ft",
		price: 7999,
		picture: "https://mobileimages.lowes.com/productimages/a4b29f66-eb7d-4afb-9e75-117829191dfc/15156887.jpg?size=pdhism",
		description: "En högpresterande studsmatta med en rostbeständig galvaniserad stålram och UV-beständig hoppmatta. Innehåller skyddsnät och stege.",
		id: randomId,
	},
	{
		name: "Gardenline 10ft Trampoline",
		price: 199,
		picture: "https://cdn.aldi-digital.co.uk//710499449336800-A.jpg?o=Ouz7GkWtqf%24JS0b4THmAF9fuyr8j&V=qItw",
		description: "En budgetvänlig studsmatta som är perfekt för små trädgårdar. Inkluderar ett skyddsnät och skumvaddering runt kanten.",
		id: randomId,
	},
	{
		name: "Hudora Fantastic Trampoline 300cm",
		price: 3999,
		picture: "https://m.media-amazon.com/images/I/81ROscHLk+L._AC_UF1000,1000_QL80_.jpg",
		description: "En högkvalitativ studsmatta med ram i galvaniserat stål och väderbeständig hoppmatta. Inkluderar ett skyddsnätskåp, stege och skydd.",
		id: randomId,
	},
	{
		name: "Plum 8ft Magnitude Trampoline",
		price: 2499,
		picture: "https://www.wickentoys.co.uk/media/catalog/product/cache/035235f776847af9b40d8d7a60de261f/3/0/30162_plum_8ft-magnitude-springsafe-trampoline.jpg",
		description: "En tålig studsmatta med en patenterad 3G-höljesdesign som böjs inåt för att hålla hoppare säkra. Inkluderar en galvaniserad stålram och stege.",
		id: randomId,
	},
	{
		name: "Skywalker Trampolines 12ft Jump N' Dunk",
		price: 3699,
		picture: "https://m.media-amazon.com/images/I/71+IQRtBkoL._AC_UF1000,1000_QL80_.jpg",
		description: "En rolig studsmatta med basketkorg och säkerhetskåpa. Inkluderar en rostbeständig ram och förstärkta T-uttag för ökad stabilitet.",
		id: randomId,
	},
	{
		name: "Super Jumper Combo Trampoline",
		price: 4999,
		picture: "https://cpsc-d8-media-prod.s3.amazonaws.com/s3fs-public/styles/recall_product/public/pic3_31.jpg?VersionId=X.IQbO1LgugxUzeixj7gprCGTAbuXDGB&itok=ZAe-tNy0",
		description: "En mångsidig studsmatta med säkerhetshölje, stege och basketkorg. Inkluderar en kraftig galvaniserad stålram och UV-beständig hoppmatta.",
		id: randomId,
	},
	{
		name: "Ultrasport Garden Trampoline 305cm",
		price: 3299,
		picture: "https://images-eu.ssl-images-amazon.com/images/I/918cQsh2QCL.jpg",
		description: "En robust studsmatta med ram i galvaniserat stål och väderbeständig hoppmatta. Inkluderar ett skyddsnät, stege och regnskydd.",
		id: randomId,
	}
]